name: glucose_companion
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.3
  crypto: ^3.0.3

  # Стан додатку
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  get_it: ^7.6.7

  # Мережеві запити
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1

  # Локальне сховище
  sqflite: ^2.3.2
  shared_preferences: ^2.2.2
  sqflite_sqlcipher: ^2.2.1
  path: ^1.8.3
  path_provider: ^2.1.2

  # Графіки та візуалізація
  fl_chart: ^0.66.2

  # Утиліти
  intl: ^0.19.0
  logger: ^2.0.2+1
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  bloc_test: ^9.1.6

flutter:
  uses-material-design: true
  assets:
    - assets/sql/
